name: FlowKit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9'
    - name: Build and Test
      run: |
        swift test
