name: FlowKit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:  
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4  
        name: commitlint  
        with:  
          fetch-depth: 0  
      - uses: wagoid/commitlint-github-action@v6.0.1  
  lint-pr:  
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v4  
      - uses: CondeNast/conventional-pull-request-action@v0.2.0  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          commitlintRulesPath: './commitlint.config.js'  
          commitTitleMatch: 'true'
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9'
    - name: Build and Test
      run: |
        swift test
